### Listar produtos
GET http://localhost:8080/produtos

### Criar produto
POST http://localhost:8080/produtos
Content-Type: application/json

{
  "nome": "Cerveja Heineken",
  "categoria": "BEBIDA",
  "preco": 12.50,
  "estoque": 50
}

### Buscar produto por id
GET http://localhost:8080/produtos/1